name: Deploy Sanity Studio

on:
  push:
    branches:
      - main

jobs:
  deploy-sanity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Cache node modules
        id: cache-node
        uses: actions/cache@v3
        with:
          path: |
            apps/cms/node_modules
            node_modules
            ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('apps/cms/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: npm ci

      - name: Deploy studio
        run: SANITY_AUTH_TOKEN=${{ secrets.SANITY_DEPLOY_TOKEN }} npm run cms:deploy -w cms