name: Hourly batch

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  batch-production:
    runs-on: ubuntu-latest
    steps:
      - name: Active pending agreements
        run: |
          curl --request POST \
          --url 'https://www.pcosnorge.no/api/vipps/agreement/batch' \
          --header 'Authorization: Bearer ${{ secrets.PRODUCTION_VIPPS_CLIENT_SECRET }}'
      - name: Capture outstanding charges
        run: |
          curl --request POST \
          --url 'https://www.pcosnorge.no/api/vipps/capture' \
          --header 'Authorization: Bearer ${{ secrets.PRODUCTION_VIPPS_CLIENT_SECRET }}'


curl --request POST --url 'https://www.pcosnorge.no/api/vipps/capture' --header 'Authorization: Bearer -wQHNDIU2A1z2ZBy24eYFmpI1_Q='